--STUDENTS
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, CREATED_DATE_TIME, UPDATED_DATE_TIME) VALUES 
("Anat", "Abdullagasim", NOW(), NOW());

--TEACHER
INSERT INTO TEACHERS (FIRST_NAME, LAST_NAME, CREATED_DATE_TIME, UPDATED_DATE_TIME) VALUES 
("Panupat", "Horma", NOW(), NOW());

--COURSES
INSERT INTO COURSES (NAME, TEACHER_ID, CREATED_DATE_TIME, UPDATED_DATE_TIME) VALUES
("Web Develop", 1, NOW(), NOW());